-- custom_scripts/screenplays/screenplays.lua (source LBG — deploy via deploy_core3_ia_bridge_vm.sh)
includeFile("../custom_scripts/screenplays/ia_spawn_tag.lua")
includeFile("../custom_scripts/screenplays/lbg_terrain_lib.lua")
includeFile("../custom_scripts/screenplays/sandbox_conv_handler.lua")
includeFile("../custom_scripts/screenplays/sandbox_screenplay.lua")
includeFile("../custom_scripts/screenplays/ia_bridge_screenplay.lua")
includeFile("../custom_scripts/screenplays/lbg_artisan_hub_screenplay.lua")
includeFile("../custom_scripts/screenplays/lbg_world_editor_screenplay.lua")
includeFile("../custom_scripts/screenplays/lbg_player_hooks.lua")
includeFile("../custom_scripts/screenplays/lbg_lost_heaven_screenplay.lua")
includeFile("../custom_scripts/screenplays/lbg_scrapaltai_world_screenplay.lua")
